// Generated by CoffeeScript 1.12.2
(function() {
  var DefaultFileIcons, FileIcons;

  DefaultFileIcons = require('./default-file-icons');

  FileIcons = (function() {
    function FileIcons() {
      this.service = new DefaultFileIcons;
    }

    FileIcons.prototype.getService = function() {
      return this.service;
    };

    FileIcons.prototype.resetService = function() {
      return this.service = new DefaultFileIcons;
    };

    FileIcons.prototype.setService = function(service) {
      this.service = service;
    };

    return FileIcons;

  })();

  module.exports = new FileIcons;

}).call(this);
