Object.defineProperty(exports, '__esModule', {
  value: true
});

/*
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the license found in the LICENSE file in
 * the root directory of this source tree.
 */

var ACTIVATE_REPOSITORY = 'ACTIVATE_REPOSITORY';
exports.ACTIVATE_REPOSITORY = ACTIVATE_REPOSITORY;
var ADD_REPOSITORY = 'ADD_REPOSITORY';
exports.ADD_REPOSITORY = ADD_REPOSITORY;
var CLOSE_VIEW = 'CLOSE_VIEW';
exports.CLOSE_VIEW = CLOSE_VIEW;
var COMMIT = 'COMMIT';
exports.COMMIT = COMMIT;
var DEACTIVATE_REPOSITORY = 'DEACTIVATE_REPOSITORY';
exports.DEACTIVATE_REPOSITORY = DEACTIVATE_REPOSITORY;
var DIFF_FILE = 'DIFF_FILE';
exports.DIFF_FILE = DIFF_FILE;
var OPEN_VIEW = 'OPEN_VIEW';
exports.OPEN_VIEW = OPEN_VIEW;
var PUBLISH_DIFF = 'PUBLISH_DIFF';
exports.PUBLISH_DIFF = PUBLISH_DIFF;
var REMOVE_REPOSITORY = 'REMOVE_REPOSITORY';
exports.REMOVE_REPOSITORY = REMOVE_REPOSITORY;
var SET_COMMIT_MODE = 'SET_COMMIT_MODE';
exports.SET_COMMIT_MODE = SET_COMMIT_MODE;
var SET_COMPARE_ID = 'SET_COMPARE_ID';
exports.SET_COMPARE_ID = SET_COMPARE_ID;
var SET_CWD_API = 'SET_CWD_API';
exports.SET_CWD_API = SET_CWD_API;
var SET_SHOULD_REBASE_ON_AMEND = 'SET_SHOULD_REBASE_ON_AMEND';
exports.SET_SHOULD_REBASE_ON_AMEND = SET_SHOULD_REBASE_ON_AMEND;
var SET_VIEW_MODE = 'SET_VIEW_MODE';
exports.SET_VIEW_MODE = SET_VIEW_MODE;
var UPDATE_ACTIVE_REPOSITORY = 'UPDATE_ACTIVE_REPOSITORY';
exports.UPDATE_ACTIVE_REPOSITORY = UPDATE_ACTIVE_REPOSITORY;
var UPDATE_COMMIT_STATE = 'UPDATE_COMMIT_STATE';
exports.UPDATE_COMMIT_STATE = UPDATE_COMMIT_STATE;
var UPDATE_DIRTY_FILES = 'UPDATE_DIRTY_FILES';
exports.UPDATE_DIRTY_FILES = UPDATE_DIRTY_FILES;
var UPDATE_FILE_DIFF = 'UPDATE_FILE_DIFF';
exports.UPDATE_FILE_DIFF = UPDATE_FILE_DIFF;
var UPDATE_HEAD_TO_FORKBASE_REVISIONS = 'UPDATE_HEAD_TO_FORKBASE_REVISIONS';
exports.UPDATE_HEAD_TO_FORKBASE_REVISIONS = UPDATE_HEAD_TO_FORKBASE_REVISIONS;
var UPDATE_PUBLISH_STATE = 'UPDATE_PUBLISH_STATE';
exports.UPDATE_PUBLISH_STATE = UPDATE_PUBLISH_STATE;
var UPDATE_SELECTED_FILES = 'UPDATE_SELECTED_FILES';
exports.UPDATE_SELECTED_FILES = UPDATE_SELECTED_FILES;