Object.defineProperty(exports, '__esModule', {
  value: true
});

/*
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the license found in the LICENSE file in
 * the root directory of this source tree.
 */

var PANEL_CREATED = 'PANEL_CREATED';
exports.PANEL_CREATED = PANEL_CREATED;
var PANEL_DESTROYED = 'PANEL_DESTROYED';
exports.PANEL_DESTROYED = PANEL_DESTROYED;
var REFRESH_TASKS = 'REFRESH_TASKS';
exports.REFRESH_TASKS = REFRESH_TASKS;
var REGISTER_BUILD_SYSTEM = 'REGISTER_BUILD_SYSTEM';
exports.REGISTER_BUILD_SYSTEM = REGISTER_BUILD_SYSTEM;
var RUN_TASK = 'RUN_TASK';
exports.RUN_TASK = RUN_TASK;
var STOP_TASK = 'STOP_TASK';
exports.STOP_TASK = STOP_TASK;
var SELECT_BUILD_SYSTEM = 'SELECT_BUILD_SYSTEM';
exports.SELECT_BUILD_SYSTEM = SELECT_BUILD_SYSTEM;
var SELECT_TASK = 'SELECT_TASK';
exports.SELECT_TASK = SELECT_TASK;
var TASK_COMPLETED = 'TASK_COMPLETED';
exports.TASK_COMPLETED = TASK_COMPLETED;
var TASK_PROGRESS = 'TASK_PROGRESS';
exports.TASK_PROGRESS = TASK_PROGRESS;
var TASK_STARTED = 'TASK_STARTED';
exports.TASK_STARTED = TASK_STARTED;
var TASK_STOPPED = 'TASK_STOPPED';
exports.TASK_STOPPED = TASK_STOPPED;
var TASK_ERRORED = 'TASK_ERRORED';
exports.TASK_ERRORED = TASK_ERRORED;
var TASKS_UPDATED = 'TASKS_UPDATED';
exports.TASKS_UPDATED = TASKS_UPDATED;
var TOOLBAR_VISIBILITY_UPDATED = 'TOOLBAR_VISIBILITY_UPDATED';
exports.TOOLBAR_VISIBILITY_UPDATED = TOOLBAR_VISIBILITY_UPDATED;
var UNREGISTER_BUILD_SYSTEM = 'UNREGISTER_BUILD_SYSTEM';
exports.UNREGISTER_BUILD_SYSTEM = UNREGISTER_BUILD_SYSTEM;