#!/usr/bin/env python

# Copyright (c) 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the LICENSE file in
# the root directory of this source tree.

'''
Writes the contents of the nuclide-installer config file to standard out,
which will look something like the following:

{
  "defaultVersion": "0.0.0",
  "packages": [
    {
      "name": "nuclide-file-tree"
    },
    {
      "name": "nuclide-flow"
    },
    {
      "name": "nuclide-hg-repository"
    }
  ]
}
'''

# Set up the logging early on in the process.
import logging
logging.basicConfig(level=logging.INFO, format='%(message)s')

# Do other ordinary imports.
import os.path
import sys

# Add the lib/ directory to $PYTHONPATH so library code can be imported.
sys.path.append(os.path.join(os.path.dirname(__file__), '../lib'))

from publishers.nuclide_installer_config import generate_config
print(generate_config())
