#!/bin/bash

cd "$(hg root)/xplat" || exit 1

DEFAULT_OUTPUT_PATH="$PWD/nuclide/pkg/nuclide-debugger-java-rpc/Build/java_debugger_server.jar"
OUTPUT_PATH="${1:-$DEFAULT_OUTPUT_PATH}"

mkdir -p "$(dirname "$OUTPUT_PATH")"
buck build nuclide-debugger-java --out "$OUTPUT_PATH"
echo "$OUTPUT_PATH"
