"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = exports.ActionTypes = void 0;

function _Dispatcher() {
  const data = _interopRequireDefault(require("../../commons-node/Dispatcher"));

  _Dispatcher = function () {
    return data;
  };

  return data;
}

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the license found in the LICENSE file in
 * the root directory of this source tree.
 *
 * 
 * @format
 */
// $FlowFixMe(>=0.53.0) Flow suppress
const ActionTypes = Object.freeze({
  CLEAR_DRAG_HOVER: 'CLEAR_DRAG_HOVER',
  CLEAR_LOADING: 'CLEAR_LOADING',
  CLEAR_SELECTION: 'CLEAR_SELECTION',
  CLEAR_SELECTION_RANGE: 'CLEAR_SELECTION_RANGE',
  COLLAPSE_NODE: 'COLLAPSE_NODE',
  COLLAPSE_NODE_DEEP: 'COLLAPSE_NODE_DEEP',
  COLLAPSE_SELECTION: 'COLLAPSE_SELECTION',
  COLLAPSE_ALL: 'COLLAPSE_ALL',
  CONFIRM_NODE: 'CONFIRM_NODE',
  COPY_FILENAMES_WITH_DIR: 'COPY_FILENAMES_WITH_DIR',
  DELETE_SELECTED_NODES: 'DELETE_SELECTED_NODES',
  DELETE_SELECTION: 'DELETE_SELECTION',
  EXPAND_NODE: 'EXPAND_NODE',
  EXPAND_SELECTION: 'EXPAND_SELECTION',
  LOAD_DATA: 'LOAD_DATA',
  SET_EXCLUDE_VCS_IGNORED_PATHS: 'SET_EXCLUDE_VCS_IGNORED_PATHS',
  EXPAND_NODE_DEEP: 'EXPAND_NODE_DEEP',
  SET_CWD: 'SET_CWD',
  SET_CWD_TO_SELECTION: 'SET_CWD_TO_SELECTION',
  SET_CWD_API: 'SET_CWD_API',
  SET_HIDE_IGNORED_NAMES: 'SET_HIDE_IGNORED_NAMES',
  SET_HIDE_VCS_IGNORED_PATHS: 'SET_HIDE_VCS_IGNORED_PATHS',
  SET_IS_CALCULATING_CHANGES: 'SET_IS_CALCULATING_CHANGES',
  SET_IGNORED_NAMES: 'SET_IGNORED_NAMES',
  SET_LOADING: 'SET_LOADING',
  SET_ROOTS: 'SET_ROOTS',
  SET_TRACKED_NODE: 'SET_TRACKED_NODE',
  SET_REMOTE_PROJECTS_SERVICE: 'SET_REMOTE_PROJECTS_SERVICE',
  CLEAR_TRACKED_NODE: 'CLEAR_TRACKED_NODE',
  CLEAR_TRACKED_NODE_IF_NOT_LOADING: 'CLEAR_TRACKED_NODE_IF_NOT_LOADING',
  KEEP_PREVIEW_TAB: 'KEEP_PREVIEW_TAB',
  OPEN_SELECTED_ENTRY: 'OPEN_SELECTED_ENTRY',
  OPEN_SELECTED_ENTRY_SPLIT: 'OPEN_SELECTED_ENTRY_SPLIT',
  OPEN_ENTRY_SPLIT: 'OPEN_ENTRY_SPLIT',
  OPEN_ADD_FOLDER_DIALOG: 'OPEN_ADD_FOLDER_DIALOG',
  OPEN_ADD_FILE_DIALOG: 'OPEN_ADD_FILE_DIALOG',
  OPEN_ADD_FILE_DIALOG_RELATIVE: 'OPEN_ADD_FILE_DIALOG_RELATIVE',
  OPEN_RENAME_DIALOG: 'OPEN_RENAME_DIALOG',
  OPEN_DUPLICATE_DIALOG: 'OPEN_DUPLICATE_DIALOG',
  OPEN_NEXT_DUPLICATE_DIALOG: 'OPEN_NEXT_DUPLICATE_DIALOG',
  OPEN_PASTE_DIALOG: 'OPEN_PASTE_DIALOG',
  START_REORDER_DRAG: 'START_REORDER_DRAG',
  END_REORDER_DRAG: 'END_REORDER_DRAG',
  REVEAL_NODE_KEY: 'REVEAL_NODE_KEY',
  REVEAL_FILE_PATH: 'REVEAL_FILE_PATH',
  OPEN_AND_REVEAL_FILE_PATH: 'OPEN_AND_REVEAL_FILE_PATH',
  OPEN_AND_REVEAL_FILE_PATHS: 'OPEN_AND_REVEAL_FILE_PATHS',
  OPEN_AND_REVEAL_DIRECTORY_PATH: 'OPEN_AND_REVEAL_DIRECTORY_PATH',
  REORDER_DRAG_INTO: 'REORDER_DRAG_INTO',
  REORDER_ROOTS: 'REORDER_ROOTS',
  MOVE_TO_NODE: 'MOVE_TO_NODE',
  SET_INITIAL_DATA: 'SET_INITIAL_DATA',
  SET_USE_PREVIEW_TABS: 'SET_USE_PREVIEW_TABS',
  SET_USE_PREFIX_NAV: 'SET_USE_PREFIX_NAV',
  SET_AUTO_EXPAND_SINGLE_CHILD: 'SET_AUTO_EXPAND_SINGLE_CHILD',
  SET_FOCUS_EDITOR_ON_FILE_SELECTION: 'SET_FOCUS_EDITOR_ON_FILE_SELECTION',
  SET_VCS_STATUSES: 'SET_VCS_STATUSES',
  SET_REPOSITORIES: 'SET_REPOSITORIES',
  SET_WORKING_SET: 'SET_WORKING_SET',
  WORKING_SET_CHANGE_REQUESTED: 'WORKING_SET_CHANGE_REQUESTED',
  SET_OPEN_FILES_WORKING_SET: 'SET_OPEN_FILES_WORKING_SET',
  SET_WORKING_SETS_STORE: 'SET_WORKING_SETS_STORE',
  START_EDITING_WORKING_SET: 'START_EDITING_WORKING_SET',
  FINISH_EDITING_WORKING_SET: 'FINISH_EDITING_WORKING_SET',
  CHECK_NODE: 'CHECK_NODE',
  UNCHECK_NODE: 'UNCHECK_NODE',
  SET_DRAG_HOVERED_NODE: 'SET_DRAG_HOVERED_NODE',
  UNHOVER_NODE: 'UNHOVER_NODE',
  SET_SELECTED_NODE: 'SET_SELECTED_NODE',
  SET_FOCUSED_NODE: 'SET_FOCUSED_NODE',
  ADD_SELECTED_NODE: 'ADD_SELECTED_NODE',
  UNSELECT_NODE: 'UNSELECT_NODE',
  RANGE_SELECT_TO_NODE: 'RANGE_SELECT_TO_NODE',
  RANGE_SELECT_UP: 'RANGE_SELECT_UP',
  RANGE_SELECT_DOWN: 'RANGE_SELECT_DOWN',
  MOVE_SELECTION_UP: 'MOVE_SELECTION_UP',
  MOVE_SELECTION_DOWN: 'MOVE_SELECTION_DOWN',
  MOVE_SELECTION_TO_TOP: 'MOVE_SELECTION_TO_TOP',
  MOVE_SELECTION_TO_BOTTOM: 'MOVE_SELECTION_TO_BOTTOM',
  CLEAR_FILTER: 'CLEAR_FILTER',
  ADD_EXTRA_PROJECT_SELECTION_CONTENT: 'ADD_EXTRA_PROJECT_SELECTION_CONTENT',
  REMOVE_EXTRA_PROJECT_SELECTION_CONTENT: 'REMOVE_EXTRA_PROJECT_SELECTION_CONTENT',
  REMOVE_ROOT_FOLDER_SELECTION: 'REMOVE_ROOT_FOLDER_SELECTION',
  SET_OPEN_FILES_EXPANDED: 'SET_OPEN_FILES_EXPANDED',
  SET_UNCOMMITTED_CHANGES_EXPANDED: 'SET_UNCOMMITTED_CHANGES_EXPANDED',
  SET_FOLDERS_EXPANDED: 'SET_FOLDERS_EXPANDED',
  INVALIDATE_REMOVED_FOLDER: 'INVALIDATE_REMOVED_FOLDER',
  SET_TARGET_NODE: 'SET_TARGET_NODE',
  UPDATE_GENERATED_STATUSES: 'UPDATE_GENERATED_STATUSES',
  ADD_FILTER_LETTER: 'ADD_FILTER_LETTER',
  REMOVE_FILTER_LETTER: 'REMOVE_FILTER_LETTER',
  UPDATE_REPOSITORIES: 'UPDATE_REPOSITORIES',
  UPDATE_ROOT_DIRECTORIES: 'UPDATE_ROOT_DIRECTORIES'
}); // Flow hack: Every FileTreeAction type must be in ActionTypes.
// $FlowFixMe(>=0.68.0) Flow suppress (T27187857)

exports.ActionTypes = ActionTypes;
'';
let instance;

class FileTreeDispatcher extends _Dispatcher().default {
  static getInstance() {
    if (!instance) {
      instance = new FileTreeDispatcher();
    }

    return instance;
  }

}

exports.default = FileTreeDispatcher;