#!/bin/bash

# Copyright (c) 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the LICENSE file in
# the root directory of this source tree.

# This will make the current directory the real path this script lives in
cd "$( cd "$(dirname $0)" ; pwd -P )" > /dev/null 2>&1
# This will make the current directory the path that contains the scripts dir
cd "$(dirname "$(readlink "$0" || printf %s "$0")")" > /dev/null 2>&1

# Use the new nuclide-server2 codepath with the '--big-dig' flag.
if [ "$1" == "--big-dig" ]; then
  shift
  # Try to enable core dumps (not doable from with Node)
  ulimit -c unlimited || true
  node ../nuclide-server2/lib/main.js "$@"
else
  python2.7 scripts/nuclide_server_manager.py "$@"
fi
