#!/usr/bin/env python

# Copyright (c) 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the LICENSE file in
# the root directory of this source tree.

from __future__ import print_function

import logging
import optparse
import os
import shutil
import subprocess
import sys
from datetime import datetime

def main():
    # Set up the logging early on in the process.
    logging.basicConfig(level=logging.INFO, format='%(message)s')

    # Parse the command-line arguments.
    parser = optparse.OptionParser(usage='usage: %prog [options]',
        description='Generate thrift code for remote file system service')

    parser.add_option('-l', '--lan', action="store", dest="language",
        choices=['js:node', 'java', 'php', 'python', 'perl', 'ruby',],
        default="js:node",
        help="Compile thrift to given language.",)
    parser.add_option('--dev', action='store_true',
        help='Generate code for development mode', default=False)
    parser.add_option('--production', action='store_true',
        help='Install only production dependencies', default=False)

    (options, args) = parser.parse_args()

    # compile thrift file and generate thrift code to target language
    print('\n Generating thrift file into source code ...')
    os.system('thrift --gen {0} -r filesystem.thrift'.format(options.language))

if __name__ == '__main__':
    main()
