#!/bin/bash

set -e

cd "$(dirname "$0")/../.."

BASE_DIR="$(pwd -P)"

SUMFILE=node_modules/package.json.sum

set +e
shasum -c $SUMFILE 2> /dev/null > /dev/null
shacode=$?
set -e

if [[ $shacode -ne 0 ]] ; then
  # Spews some warnings
  npm install 2> /dev/null 1>&2

  shasum package.json > $SUMFILE
fi

node "$BASE_DIR/node_modules/.bin/eslint" --config "$BASE_DIR/.eslintrc" "$@"
