#!/usr/bin/env python

# Copyright (c) 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the LICENSE file in
# the root directory of this source tree.

# This script installs dependencies from a zip file created by ./zip_dependencies.
# This is different than ./setup, which uses `npm install` to fetch dependencies
# from npmjs.org, which means it requires internet access to install dependencies.
# This script is ideal for use in restricted build environments, such as CI systems
# that try to lock things down to enforce a hermetic, reproducible build.

# Set up the logging early on in the process.
import logging
logging.basicConfig(level=logging.INFO, format='%(message)s')

# Do other ordinary imports.
import os.path
import sys

# Add the lib/ directory to $PYTHONPATH so library code can be imported.
sys.path.append(os.path.join(os.path.dirname(__file__), '../lib'))

# Parse the command-line arguments.
import atom
import optparse
parser = optparse.OptionParser(usage='usage: %prog [options]',
                               description='Install dependencies for Node and Atom packages')
parser.add_option('--npm-directory', type=str, help='directory with the structure of a ~/.npm directory')
atom.add_args_for_env_setup(parser)
options, args = parser.parse_args(sys.argv[1:])

atom.add_node_executables_to_path(parser)

# Perform the offline installation.
from package_manager import PackageManager
from offline_installer import OfflineInstaller

package_manager = PackageManager()
npm_directory = options.npm_directory
installer = OfflineInstaller(package_manager, npm_directory)
installer.install()
