#!/bin/bash

set -e

cd "$(dirname "$0")/../.."

BASE_DIR="$(pwd -P)"

echo "Checking for cycles in modules ..."
find "$BASE_DIR/lib" "$BASE_DIR/pkg" \
    -name sample -prune \
    -o -name spec -prune \
    -o -name VendorLib -prune \
    -o -name scripts -prune \
    -o -name nuclide-external-interfaces -prune \
    -o -name '*.js' -print | xargs "$BASE_DIR/node_modules/.bin/sabor"
