#!/usr/bin/env python

# Copyright (c) 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the LICENSE file in
# the root directory of this source tree.

# Set up the logging early on in the process.
import logging
logging.basicConfig(level=logging.INFO, format='%(message)s')

# Do other ordinary imports.
import os.path
import sys

# Add the lib/ directory to $PYTHONPATH so library code can be imported.
sys.path.append(os.path.join(os.path.dirname(__file__), '../lib'))

# Parse the command-line arguments.
import atom
import optparse
parser = optparse.OptionParser(usage='usage: %prog [options]',
                               description='Run all tests for Nuclide')
# If you are certain that all of the packages have their dependencies installed correctly,
# skipping the installation step can save a considerable amount of time.
parser.add_option('--no-install', action='store_true', default=False, help='Skip `./setup` step')
parser.add_option('--no-atom', action='store_true', default=False, help='Exclude packages that depend on Atom')
atom.add_args_for_env_setup(parser)
options, args = parser.parse_args(sys.argv[1:])

# When testing the server packages, only `node` and `npm` need to be on the $PATH.
include_apm = not options.no_atom
atom.add_node_executables_to_path(parser, include_apm)

# Run ./setup, if appropriate.
if not options.no_install:
    # Run setup.
    import subprocess
    setup = os.path.join(os.path.dirname(__file__), 'setup')
    setup_args = [setup]
    if options.atom_app_dir:
        setup_args += ['--atom-app-dir', options.atom_app_dir]
    if options.no_atom:
        setup_args += ['--no-atom']
    subprocess.check_call(setup_args)

# Create the constructor args for JsTestRunner.
from package_manager import PackageManager
package_manager = PackageManager()

# Create and run JsTestRunner.
from js_test_runner import JsTestRunner
test_runner = JsTestRunner(package_manager, include_apm)
test_runner.run_tests()
