#!/usr/bin/env python

# Copyright (c) 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the LICENSE file in
# the root directory of this source tree.

import logging
import optparse
import os
import os.path
import subprocess
import sys
from datetime import datetime

# Set up the logging early on in the process.
logging.basicConfig(level=logging.INFO, format='%(message)s')

# Add the lib/ directory to $PYTHONPATH so library code can be imported.
sys.path.append(os.path.join(os.path.dirname(__file__), '../lib'))

from dependencies import check_dependencies
from js_test_runner import JsTestRunner
from package_manager import PackageManager, NUCLIDE_PATH

# Parse the command-line arguments.
parser = optparse.OptionParser(
    usage='usage: %prog [options] [package-names or integration-tests]',
    description='Run all tests for Nuclide. '
                'Can explicitly list individual packages or integration-tests '
                'to run.')
parser.add_option('--dev', action='store_true',
                  help='Target ~/.atom/dev/packages/ instead of ~/.atom/packages',
                  default=False)
parser.add_option('--no-module-cycle-check', action='store_true',
                  help='Skip `./module_cycle_check` step')
parser.add_option('--verbose', action='store_true',
                  help='Verbose output')
parser.add_option('--no-atom', action='store_true',
                  help='Exclude packages that depend on Atom')
parser.add_option('--parallel', action='store_true',
                  help='Run parallelable tests in parallel')
parser.add_option('--no-version', action='store_true',
                  help='Ignore mismatched versions of Atom/npm/node/apm')
parser.add_option('--run-integration-tests', action='store_true',
                  help='Only run tests in Nuclide/spec')
parser.add_option('--continue-on-errors', action='store_true',
                  help='Run all tests, regardless of failures')

options, args = parser.parse_args(sys.argv[1:])

try:
    from fb.pre_setup import fb_pre_setup
    disable_fb_update = not options.dev
    fb_pre_setup(disable_fb_update)
except ImportError as _:
    pass

def run(name, cmd):
    try:
        start = datetime.now()
        logging.info('Running %s...', name)
        subprocess.check_call(cmd, cwd=NUCLIDE_PATH)
    except (subprocess.CalledProcessError, KeyboardInterrupt):
        logging.info('FAILED: %s', name)
        sys.exit(1)
    finally:
        end = datetime.now()
        logging.info('%s took %s seconds.', name, (end - start).seconds)

# Some tests compare created files and all their properties to an oracle. If
# they are created with a different umask, then the permissions are different
# and the tests fail.
os.umask(022)

package_manager = PackageManager()
test_runner = JsTestRunner(
    package_manager,
    not options.no_atom,
    args,
    options.verbose,
    options.parallel,
    options.continue_on_errors,
)

if not options.no_version:
    check_dependencies(not options.no_atom)

if options.run_integration_tests:
    test_runner.run_integration_tests()
else:
    run('lint_packages', ['scripts/dev/lint_packages'])
    run('eslint', ['node_modules/.bin/eslint', '--max-warnings=0', '.'])
    run('flow', ['flow', 'check', '--show-all-errors'])
    if not options.no_module_cycle_check:
        run('module_cycle_check', ['scripts/dev/module_cycle_check'])
    test_runner.run_unit_tests()
