#!/usr/bin/env python

# Copyright (c) 2015-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the LICENSE file in
# the root directory of this source tree.

# This script works assuming that you have already installed all of the dependencies
# you need to zip up in your ~/.npm directory. Running ./setup before running this
# script is the best way to ensure that all necessary dependencies are available locally.

# Set up the logging early on in the process.
import logging
logging.basicConfig(level=logging.INFO, format='%(message)s')

# Do other ordinary imports.
import os.path
import sys

# Add the lib/ directory to $PYTHONPATH so library code can be imported.
sys.path.append(os.path.join(os.path.dirname(__file__), '../lib'))

# Parse the command-line arguments.
import atom
import optparse
parser = optparse.OptionParser(usage='usage: %prog [options]',
                               description='Zip the dependencies for Nuclide into a directory')
parser.add_option('--output-dir', type=str, help='where to write output')
atom.add_args_for_env_setup(parser)
options, args = parser.parse_args(sys.argv[1:])

atom.add_node_executables_to_path(parser)

output_dir = None
if options.output_dir:
    output_dir = os.path.realpath(options.output_dir)
else:
    import tempfile
    output_dir = tempfile.mkdtemp()
print('Output directory is %s' % output_dir)

# Run the dependency finder.
from package_manager import PackageManager
from dependency_finder import DependencyFinder

package_manager = PackageManager()
dot_npm_dir = os.path.join(os.environ['HOME'], '.npm')

dependency_finder = DependencyFinder(package_manager, dot_npm_dir)
dependency_finder.write_dependencies(output_dir)
